![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
# My code
x = np.array([4, 3, 2, 1])
print(x)
print(type(x))
print(dir(x))

[4 3 2 1]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand_

In [5]:
# My code
print(x.argmin())
print(x.argmax())
print(x.all())
print(x.any())
print(x.argsort())

3
0
True
True
[3 2 1 0]


In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
b = np.array([0, .5, 1, 1.5, 2])

In [8]:
a[0], a[1]

(1, 2)

In [9]:
a[0:]

array([1, 2, 3, 4])

In [10]:
a[1:3]

array([2, 3])

In [11]:
a[1:-1]

array([2, 3])

In [12]:
a[::2]

array([1, 3])

In [13]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [15]:
# it's selecting indexes 0, 2 and last and returning an array with the values from those indexes
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [16]:
a

array([1, 2, 3, 4])

In [17]:
a.dtype

dtype('int64')

In [18]:
# My code
c = np.array(['testing', 'text', 'on numeric python', "I shouldn't"])

In [19]:
# My code
print(c)

['testing' 'text' 'on numeric python' "I shouldn't"]


In [20]:
# My code
c.dtype

dtype('<U17')

In [21]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
b.dtype

dtype('float64')

In [23]:
np.array([1, 2, 3, 4], dtype=np.float)

/tmp/ipykernel_5635/217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [24]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [25]:
c = np.array(['a', 'b', 'c'])

In [26]:
c.dtype

dtype('<U1')

In [27]:
d = np.array([{'a': 1}, sys])

In [28]:
d.dtype

dtype('O')

In [29]:
# My code --- if it's the same why use sys as the second argument above????
e = np.array([{'key': 5}])
print(e)
e.dtype

[{'key': 5}]


dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [30]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [31]:
# 2 arrays of 3 values each
A.shape

(2, 3)

In [32]:
# ndim = number of dimentions 
A.ndim

2

In [33]:
# the number of values in total
A.size

6

In [34]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [35]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [36]:
B.shape

(2, 2, 3)

In [37]:
B.ndim

3

In [38]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [39]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/tmp/ipykernel_5635/548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [40]:
C.dtype

dtype('O')

In [41]:
C.shape

(2,)

In [42]:
C.size

2

In [43]:
type(C[0])

list

In [44]:
# My code -- testing dtype argument as suggested by the error message when declaring C
D = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
], dtype='object')

In [45]:
print(D)
print(C)

[list([[12, 11, 10], [9, 8, 7]]) list([[6, 5, 4]])]
[list([[12, 11, 10], [9, 8, 7]]) list([[6, 5, 4]])]


In [46]:
D.size

2

In [47]:
D.shape

(2,)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [48]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [49]:
A[1]

array([4, 5, 6])

In [50]:
A[1][0]

4

In [51]:
# A[d1, d2, d3, d4]

In [52]:
A[1, 0]

4

In [53]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [55]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [56]:
A[:2, 2:]

array([[3],
       [6]])

In [57]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
A[1] = np.array([10, 10, 10])

In [59]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [60]:
A[2] = 99

In [61]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [62]:
a = np.array([1, 2, 3, 4])

In [63]:
a.sum()

10

In [64]:
a.mean()

2.5

In [65]:
a.std()

1.118033988749895

In [66]:
a.var()

1.25

In [67]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [68]:
A.sum()

45

In [69]:
A.mean()

5.0

In [70]:
A.std()

2.581988897471611

In [71]:
A.sum(axis=0)

array([12, 15, 18])

In [72]:
A.sum(axis=1)

array([ 6, 15, 24])

In [73]:
A.mean(axis=0)

array([4., 5., 6.])

In [74]:
A.mean(axis=1)

array([2., 5., 8.])

In [75]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [76]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [77]:
# numpy.arrange(start, stop, step, dtype) 
# start default is 0
# stop is non-inclusive
a = np.arange(4)

In [78]:
a

array([0, 1, 2, 3])

In [79]:
a + 10

array([10, 11, 12, 13])

In [80]:
a * 10

array([ 0, 10, 20, 30])

In [81]:
a

array([0, 1, 2, 3])

In [82]:
a += 100

In [83]:
a

array([100, 101, 102, 103])

In [84]:
l = [0, 1, 2, 3]

In [85]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [86]:
a = np.arange(4)

In [87]:
a

array([0, 1, 2, 3])

In [88]:
b = np.array([10, 10, 10, 10])

In [89]:
b

array([10, 10, 10, 10])

In [90]:
a + b

array([10, 11, 12, 13])

In [91]:
# If either a or b is 0-D (scalar), a * b is preferred.
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [92]:
a = np.arange(4)

In [93]:
a

array([0, 1, 2, 3])

In [94]:
a[0], a[-1]

(0, 3)

In [95]:
a[[0, -1]]

array([0, 3])

In [96]:
a[[True, False, False, True]]

array([0, 3])

In [97]:
a

array([0, 1, 2, 3])

In [98]:
a >= 2

array([False, False,  True,  True])

In [99]:
a[a >= 2]

array([2, 3])

In [100]:
a.mean()

1.5

In [101]:
a[a > a.mean()]

array([2, 3])

In [102]:
a[~(a > a.mean())]

array([0, 1])

In [103]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [104]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [105]:
A = np.random.randint(100, size=(3, 3))

In [106]:
A

array([[ 2, 66, 86],
       [64, 15, 62],
       [54, 79, 62]])

In [107]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 2, 86, 15, 54, 62])

In [108]:
A > 30

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [109]:
A[A > 30]

array([66, 86, 64, 62, 54, 79, 62])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [110]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [111]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

# Dot product of two arrays.
- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
- If both a and b are 2-D arrays, it is matrix multiplication
- If either a or b is 0-D (scalar), it is equivalent to multiply
- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.
- If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b

## Syntaxis.
numpy.dot(a, b, out=None)
- a : array_like
- b : array_like
- out : ndarray, optional, Output argument. This must have the exact kind that would be returned if it was not used. is a performance feature. Therefore, if these conditions are not met, an exception is raised

In [112]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In NumPy, the @ operator means matrix multiplication.

In [113]:
# If both a and b are 2-D arrays, a @ b is preferred.
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

# numpy.ndarray.T
Attribute

Same as self.transpose().

Reverse or permute the axes of an array; returns the modified array.

Returns a view of the array with axes transposed.

For a 1-D array this has no effect, as a transposed vector is simply the same vector.

In [114]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [115]:
B.shape

(3, 2)

In [116]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [117]:
B.T.shape

(2, 3)

Notice the shape is inverted

In [118]:
W = np.array([1, 2, 3, 4, 5])
W

array([1, 2, 3, 4, 5])

In [119]:
W.T

array([1, 2, 3, 4, 5])

In [120]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [122]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [123]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [124]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [125]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [126]:
np.dtype(float).itemsize

8

### Lists are even larger

In [127]:
# A one-element list
sys.getsizeof([1])

64

In [128]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [129]:
l = list(range(100000))

In [130]:
a = np.arange(100000)

In [131]:
%time np.sum(a ** 2)

CPU times: user 1.41 ms, sys: 316 µs, total: 1.72 ms
Wall time: 994 µs


333328333350000

In [132]:
%time sum([x ** 2 for x in l])

CPU times: user 49.9 ms, sys: 0 ns, total: 49.9 ms
Wall time: 70 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

# numpy.random.random

## syntax: 
random.random(size=None)

size : int or tuple of ints, optional

Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn.

## Return:
random floats in the half-open interval [0.0, 1.0). Alias for random_sample

## Note:
New code should use the random method of a default_rng() instance instead;

By default, Generator uses bits provided by PCG64 which has better statistical properties than the legacy MT19937 used in RandomState.

``` python
# Do this (new version)
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(10)
more_vals = rng.standard_normal(10)

# instead of this (legacy version)
from numpy import random
vals = random.standard_normal(10)
more_vals = random.standard_normal(10)
```

In [133]:
np.random.random()

0.21378232862868396

In [134]:
np.random.random(size=2)

array([0.20919247, 0.16977965])

In [135]:
np.random.random(2)

array([0.12737148, 0.91449915])

In [136]:
np.random.random((2,3,4))

array([[[0.30809414, 0.47453537, 0.56271411, 0.56287418],
        [0.01120288, 0.73584308, 0.73440584, 0.3828834 ],
        [0.26980755, 0.68587828, 0.01070768, 0.96883416]],

       [[0.50568645, 0.18636602, 0.08956821, 0.74444334],
        [0.96168746, 0.24617751, 0.95279571, 0.36912891],
        [0.35514597, 0.17238556, 0.07692889, 0.80287989]]])

In [137]:
np.random.random(size=(2,3,4))

array([[[0.23351594, 0.88642894, 0.1097436 , 0.05274754],
        [0.71902782, 0.07802469, 0.20401626, 0.27367754],
        [0.21405336, 0.89981502, 0.40992499, 0.45266597]],

       [[0.21450963, 0.93338886, 0.80570738, 0.63349371],
        [0.38863416, 0.39382048, 0.74205744, 0.22280805],
        [0.75207483, 0.04759608, 0.1318905 , 0.49854288]]])

# numpy.random.normal
Draw random samples from a normal (Gaussian) distribution.

## Syntax:
random.normal(loc=0.0, scale=1.0, size=None)

<dl>
    <dt><b>loc : float or array_like of floats</b></dt>
    <dd>Mean (“centre”) of the distribution.</dd>
    <dt><b>scale : float or array_like of floats</b></dt>
    <dd>Standard deviation (spread or “width”) of the distribution. Must be non-negative.</dd>
    <dt><b>size : int or tuple of ints, optional</b></dt>
    <dd>Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.</dd>
</dl>

## Note:
New code should use the normal method of a default_rng() instance instead

Check Note above

In [138]:
np.random.normal()

0.07411700949277056

In [139]:
np.random.normal(1.0, 10.0)

-6.539302541983911

In [140]:
np.random.normal(size=2)

array([-0.00770511, -2.30728199])

# numpy.random.rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

## Syntax:
random.rand(d0, d1, ..., dn)
<dl>
    <dt><b>d0, d1, …, dn : int, optional</b></dt>
    <dd>The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.</dd>
</dl>

In [141]:
np.random.rand()

0.2966521609693815

In [142]:
np.random.rand(2)

array([0.07667778, 0.60500673])

In [143]:
np.random.rand(2, 4)

array([[0.75956403, 0.70547565, 0.16590497, 0.00264054],
       [0.57444593, 0.03251587, 0.19843267, 0.65085483]])

---
### `arange`

# numpy.arange
Return evenly spaced values within a given interval.

For integer arguments the function is roughly equivalent to the Python built-in range, but returns an ndarray rather than a range instance.

When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.
## Syntax:
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
<dl>
    <dt><b>start : integer or real, optional</b></dt>
    <dd>Start of interval. The interval includes this value. The default start value is 0.</dd>
    <dt><b>stop : integer or real</b></dt>
    <dd>End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.</dd>
    <dt><b>step : integer or real, optional</b></dt>
    <dd>Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.</dd>
    <dt><b>dtype : dtype, optional</b></dt>
    <dd>The type of the output array. If dtype is not given, infer the data type from the other input arguments.</dd>
    <dt><b>like : array_like, optional</b></dt>
    <dd>Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.</dd>
</dl>


In [144]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [146]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

# numpy.reshape
Gives a new shape to an array without changing its data.

## Syntax:
numpy.reshape(a, newshape, order='C')
<dl>
    <dt><b>a : array_like</b></dt>
    <dd>Array to be reshaped.</dd>
    <dt><b>newshape : int or tuple of ints</b></dt>
    <dd>The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.</dd>
    <dt><b>order{‘C’, ‘F’, ‘A’}, optional</b></dt>
    <dd>Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.</dd>
</dl>

In [147]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [148]:
# this is the same as above
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [149]:
# this is the same as above
np.reshape(np.arange(10), (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [150]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

# numpy.linspace
Returns num evenly spaced samples, calculated over the interval

## Syntax:
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
<dl>
    <dt><b>start : array_like</b></dt>
    <dd>The starting value of the sequence.</dd>
    <dt><b>stop : array_like</b></dt>
    <dd>The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.</dd>
    <dt><b>num : int, optional</b></dt>
    <dd>Number of samples to generate. Default is 50. Must be non-negative.</dd>
    <dt><b>endpoint : bool, optional</b></dt>
    <dd>If True, stop is the last sample. Otherwise, it is not included. Default is True.</dd>
    <dt><b>retstep : bool, optional</b></dt>
    <dd>If True, return (samples, step), where step is the spacing between samples.</dd>
    <dt><b>dtype : dtype, optional</b></dt>
    <dd>The type of the output array. If dtype is not given, the data type is inferred from start and stop. The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.</dd>
</dl>

In [151]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [152]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [153]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

# numpy.zeros
Return a new array of given shape and type, filled with zeros.

## Syntax:
numpy.zeros(shape, dtype=float, order='C', *, like=None)
<dl>
    <dt><b>shape : int or tuple of ints</b></dt>
    <dd>Shape of the new array</dd>
    <dt><b>dtype : data-type, optional</b></dt>
    <dd>The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.</dd>
    <dt><b>order : {‘C’, ‘F’}, optional, default: ‘C’</b></dt>
    <dd>Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.</dd>
    <dt><b>like : array_like, optional</b></dt>
    <dd>Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.</dd>
</dl>

In [154]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [155]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [169]:
# np.zeros((3, 3), dtype=np.int)
# DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself.
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Bad pipe message: %s [b'\n\xfb\xd9\xc1\xe0[x\xe4waFB\xe2\xebq\xa4+\x03 \x8f\xa9\x0c\xf2\xc5\x1a\x98\xeb\xd1\xf2\x94\xf6\x10i\xc2i\x14\x869\xb1\x97g\xf1\x86\x8b\xc8\x81.\x1e\xcc&\xb6\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05']
Bad pipe message: %s [b'\x04\x01\x05\x01\x06\x01\x00']
Bad pipe message: %s [b"\x03\x02\x03\x04\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 nM\x8d'\x1a\x86\xc1\xe1\xa5p\x18+\xd8(\xb6z\xbd\x04\xb9w\xfe\xda"]
Bad pipe message: %s [b'7\xb7x\x8e]\xa9|\xec*\xa1@J\x02\x12z\x0e\xdf', b'\x00\xa2\xc0\x14\xc0\n\x009\x008\x007\x006\x00\x88\x00\x87\x00\x86\x00\x85\xc0\x19\x00:\x00\x89\xc0\x0f\xc0\x05\x005\x00\x84\xc0\x13\xc0\t\x003\x002\x001\x000\x00\x9a\x00\x99\x00\x98\x00\x97\x00E\x0

# numpy.ones
Return a new array of given shape and type, filled with ones.

## Syntax:
numpy.ones(shape, dtype=None, order='C', *, like=None)
<dl>
    <dt><b>shape : int or sequence of ints</b></dt>
    <dd>Shape of the new array</dd>
    <dt><b>dtype : data-type, optional</b></dt>
    <dd>The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.</dd>
    <dt><b>order : {‘C’, ‘F’}, optional, default: ‘C’</b></dt>
    <dd>Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.</dd>
    <dt><b>like : array_like, optional</b></dt>
    <dd>Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.</dd>
</dl>

In [157]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [158]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# numpy.empty
Return a new array of uninitialized (arbitrary) data of the given shape, dtype, and order. Object arrays will be initialized to None.

## Syntax:
numpy.empty(shape, dtype=float, order='C', *, like=None)
<dl>
    <dt><b>shape : int or sequence of ints</b></dt>
    <dd>Shape of the new array</dd>
    <dt><b>dtype : data-type, optional</b></dt>
    <dd>The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.</dd>
    <dt><b>order : {‘C’, ‘F’}, optional, default: ‘C’</b></dt>
    <dd>Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.</dd>
    <dt><b>like : array_like, optional</b></dt>
    <dd>Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.</dd>
</dl>

In [159]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [160]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

# numpy.identity
Return the identity array.

The identity array is a square array with ones on the main diagonal.

## Syntax:
numpy.identity(n, dtype=None, *, like=None)
<dl>
    <dt><b>n : int</b></dt>
    <dd>Number of rows (and columns) in n x n output.</dd>
    <dt><b>dtype : data-type, optional</b></dt>
    <dd>Data-type of the output. Defaults to float.</dd>
    <dt><b>like : array_like, optional</b></dt>
    <dd>Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.</dd>
</dl>

In [161]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# numpy.eye
Return a 2-D array with ones on the diagonal and zeros elsewhere.

## Syntax:
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
<dl>
    <dt><b>N : int</b></dt>
    <dd>Number of rows in the output.</dd>
    <dt><b>M : int, optional</b></dt>
    <dd>Number of columns in the output. If None, defaults to N.</dd>
    <dt><b>k : int, optional</b></dt>
    <dd>Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.</dd>
    <dt><b>dtype : data-type, optional</b></dt>
    <dd>Data-type of the returned array.</dd>
    <dt><b>order : {‘C’, ‘F’}, optional</b></dt>
    <dd>Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.</dd>
    <dt><b>like : array_like, optional</b></dt>
    <dd>Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.</dd>
<dl>

In [162]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [163]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [164]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [165]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [166]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)